version: '2.1'

services:
  test-node-docker:
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    image: test-node-docker
    build: .
    ports:
      - 3000:3000
      - 9229:9229
    command: npm start